name: test

on:
  push:
    branches: [master]
  pull_request: null
  workflow_dispatch: null

env:
  FOUNDRY_PROFILE: ci

jobs:
  trunk:
    name: Trunk project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: forge-build

      - name: Run Trunk check
        uses: trunk-io/trunk-action@v1
        id: trunk-check

  foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge format check
        run: |
          forge fmt --check
        id: forge-check

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: forge-build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: forge-coverage

      - name: Enforce minimum coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: lcov.info
          min_coverage: 100
          exclude: test/** src/test/** src/samples/** src/utils/** src/interfaces/**

  hardhat:
    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Hardhat
        run: |
          npm ci

      - name: Run Hardhat build
        run: |
          npx hardhat compile
        id: hardhat-build

      - name: Run Hardhat tests
        run: |
          npx hardhat test
        id: hardhat-test
